In [1]:
import pandas as pd

In [2]:
# AGREGAR NUEVA COLUMNA A UN DATAFRAME

In [3]:
# Leyendo el archivo csv
df_examenes = pd.read_csv("StudentsPerformance.csv")
df_examenes

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  
0                      none          72             72             74  
1                 completed          69             90             88  
2                      none          90             95             93  
3                      none          47             57             44  
4                      none          76             78             75  
..                      ...         ...            ...            ...  
995               completed          88             99             95  
996                    none          62             55             55  
997               completed          59             71             65  
998               completed          68             78             77  
999                    none          77             86             86  

[1000 rows x 8 columns]

In [4]:
df_examenes.head()

gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [5]:
# Agregar una nueva columna con un valor

In [6]:
df_examenes["languaje score"] = 70

In [7]:
df_examenes

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  \
0                      none          72             72             74   
1                 completed          69             90             88   
2                      none          90             95             93   
3                      none          47             57             44   
4                      none          76             78             75   
..                      ...         ...            ...            ...   
995               completed          88             99             95   
996                    none          62             55             55   
997               completed          59             71             65   
998               completed          68             78             77   
999                    none          77             86             86   

     languaje score  
0                70  
1                70  
2                70  
3                70  
4                70  
..              ...  
995              70  
996              70  
997              70  
998              70  
999              70  

[1000 rows x 9 columns]

In [9]:
# La particularidad es que de esta forma se asigna de forma constante para todas las filas
# Por lo tanto hay que buscar otra forma de emular otro comportamiento

In [10]:
# Agregar una nueva columna con un array

In [11]:
# importar numpy
import numpy as np

In [13]:
# Crear un array de 1000 elementos
# Porque este dataframe tiene 1000 filas
np.arange(0, 1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [14]:
len(np.arange(0, 1000))

1000

In [15]:
# Efectivamente son 1000 elementos los que tiene el array

In [17]:
# Crear un array de 1000 elementos
puntaje_lenguaje = np.arange(0, 1000)

In [18]:
# Tamaño del array
len(puntaje_lenguaje)

1000

In [19]:
# agregar una nueva columna al dataframe con un array
df_examenes["languaje score"] = puntaje_lenguaje
df_examenes

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  \
0                      none          72             72             74   
1                 completed          69             90             88   
2                      none          90             95             93   
3                      none          47             57             44   
4                      none          76             78             75   
..                      ...         ...            ...            ...   
995               completed          88             99             95   
996                    none          62             55             55   
997               completed          59             71             65   
998               completed          68             78             77   
999                    none          77             86             86   

     languaje score  
0                 0  
1                 1  
2                 2  
3                 3  
4                 4  
..              ...  
995             995  
996             996  
997             997  
998             998  
999             999  

[1000 rows x 9 columns]

In [21]:
# Ahora no tenemos valores constantes para la nueva columna, sino, valores secuenciales
# Sin embargo, para esta columna buscamos valores que tengan otro comportamiento
# no uno secuencial de forma ascendente, sino, uno aleatorio o random

In [24]:
# Crear números enteros aleatorios entre 1 y 100
np.random.randint(1, 100+1, size=1000)
# primer argumento => valor de inicio de los números aleatorios (inclusivo)
# segundo argumento => valor límite de los números aleatorios (exclusivo)
# tercer argumento => tamaño del array

array([ 40,  11,  86,  31,  93,  14,  53,   6,  92,  66,  95,  86,  34,
        55,  77,  34,  99,  17,  16,  66,  54,  91,  21,  55,  95,  46,
        64,  66,  57,  29,  46,  61,  11,  83,  37,  14,  66,   2,  89,
        40,  19,  16,  36,   7,  96,  51,  12,  13,   8,  71,  38,  55,
        48,  88,  43,  42,  52,  22,  55,  40,  91,  97,  97,  44,  90,
        60,  30,   5,  49,  49,  61,  88,   4,  85,  30,   4,  23,   8,
        54,  19,  30,  20,  42,  66,  16,  52,  88,  12,  33,  48,  86,
        79,  96,  13,   5,  43,  95,  18,  31,  50,  42,  87,   6,  42,
        41,  50,  78,  99,   9,  18,  53,  83,  17,  80,  12,  21,  56,
        33,  83,  44,  51,  10,   8,  60,  72,  76,  50,  50,  61,  80,
        59,  44,  74,  53,  54,  94, 100,   2,  24,  92,  89,  38,  21,
        77,  56,   3,  98,  93,  36,  72,  52,   7,  72,  91,  60,  42,
        61,  78,   8,   2,  30,  54,  13,  34,   5,  14,   4,  35,  24,
        67,  62,  86,  70,  28,  77,  38,  32,  99,  74,  58,  6

In [25]:
# Nos devuelve un array de 1000 elementos con valores aleatorios desde 1 hasta 100
# Verificamos
len(np.random.randint(1, 100+1, size=1000))

1000

In [26]:
# Creo la lista de 1000 elementos con valores aleatorios
puntaje_lenguaje_random = np.random.randint(1, 100+1, size=1000)

In [27]:
# Agrego la nueva columna 'languaje_score' al dataframe con el array de valores aleatorios
df_examenes["languaje_score"] = puntaje_lenguaje_random
df_examenes

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  \
0                      none          72             72             74   
1                 completed          69             90             88   
2                      none          90             95             93   
3                      none          47             57             44   
4                      none          76             78             75   
..                      ...         ...            ...            ...   
995               completed          88             99             95   
996                    none          62             55             55   
997               completed          59             71             65   
998               completed          68             78             77   
999                    none          77             86             86   

     languaje score  languaje_score  
0                 0              47  
1                 1              94  
2                 2              96  
3                 3              10  
4                 4              78  
..              ...             ...  
995             995              61  
996             996               8  
997             997              63  
998             998              57  
999             999              32  

[1000 rows x 10 columns]

In [28]:
# Crear números aleatorios entre 1 y 100
np.random.uniform(1, 100+1, size=1000)

array([ 84.28372669,  59.37369251,  89.35281826,  15.24332155,
        80.89114893,  83.04398852,  43.23498053,  16.74938936,
        79.82557248,   5.95459531,  36.64058859,  13.64744948,
        39.0328999 ,  17.72711225,  68.22129074,  88.52830284,
        75.58637772,  29.67171533,  94.65219378,  49.80643733,
        22.15557753,  42.70395453,  31.96788536,  12.02599386,
        53.54766811,  42.24840351,  95.94641666,  88.85915676,
        65.24855046,  41.07277055,  51.93444721,  46.72264322,
        36.68699574,  80.81445524,  72.95642195,  17.87546203,
        23.71587247,  35.97573505,  36.15956995,  27.20163373,
         4.67964309,   5.71934978,  88.80942298,  97.51176598,
        99.89220268,  13.80384148,  31.44746732,  75.77831364,
        79.40042018,   9.34065017,  52.32593567,  70.28617611,
        62.14221938,   9.51428849,  59.59078835,  68.35684393,
        47.87033106,  29.40739995,  48.47427587,  47.95774431,
        75.76946055,  25.11305661,  93.21615126,  80.03